### PR TITLE
Upgrade meshkit with meshmodel changes

### PR DESCRIPTION
**Pull request by lolverae**
Signed-off-by: lolverae <alberto.olvera.espinosa@gmail.com>

**Description**

This PR repeats whats been done on the Linkerd adapter https://github.com/meshery/meshery-istio/pull/532]

**Notes for Reviewers**
Follow up of https://github.com/meshery/meshery-linkerd/pull/457

**[Signed commits](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Very good, @lolverae 👏

**Comment by leecalcote** [comment]
@Revolyssup please give this a time slice today. A new adapter release is needed after this PR merges.

**Comment by leecalcote** [comment]
> @Revolyssup please give this a time slice today. A new adapter release is needed after this PR merges.

Tomorrow is a new day...

**Review by b0id — APPROVED** [review]
This looks very straightforward.  I like the way @lolverae does things.

**Review by Revolyssup — APPROVED** [review]

**Pull request merged**
